import os
from dotenv import load_dotenv
from google import genai

# load environment variables from .env file
#This allows us to keep sensitive configuration outside the Python source code;
load_dotenv()
api_key=os.getenv("GEMINI_API_KEY")
gemini_model=os.getenv("GEMINI_MODEL")

# Validate the Gemini API key is available before creating the GEMINI client
if not api_key:
    raise ValueError("GEMINI_API_KEY is not configured.")

#Create the Gemini API client
client=genai.Client(api_key=api_key)

# Define the generation configuration
# max_output_tokens: TLimits the max amount of output generated by Gemini
# thinking_level: controls the amount of model reasoning effort used for request

generation_config={
    'max_output_tokens':1000,
    'thinking_level': 'medium'
}

student_name=input("Student name: ")
education=input("Education: ")
skills=input("Your current technical skills(comma separated): ")
projects=input("Projects (comma separated): ")
experience=input("Experience / Internship if any: ")
target_role=input("Target Job role: ")

user_input=input("Enter your prompt: ")

student_context=f"""
STUDENT PROFILE

Name: {student_name}
Education: {education}
Technical Skills: {skills}
Projects: {projects}
Experience/Internship: {experience}
Target Job Role: {target_role}
"""

# System Prompt
#Prompt Engineering
career_prompt=f"""
ROLE:
You are an AI career advisor for post-grad students

CONTEXT: 
CareerTwin helps students understand software engineering career paths, required technical skills, learning 
priorities, projects and interview preparation.

TASK:
Answer the student's career related question clearly and practically. Give revommendations that are relevant 
to the student's career goal

CONSTRAINTS:
- Do not provide unrealted information
- Do not assume skills that the stduent has not mentioned
- Prefer practical and actionable recommendations
- Keep the response concise and easy to understand

{student_context}

STUDENT QUESTION:
{user_input}
"""

# Send our request to the Gemini.
response=client.interactions.create(
    model=gemini_model,
    input=user_input,
    generation_config=generation_config,
)

print("==GEMINI==")
print(response.output_text)